FROM ruby:2.6.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /app
WORKDIR /app
COPY ./Gemfile /app/Gemfile
COPY ./Gemfile.lock /app/Gemfile.lock
RUN bundle install

COPY . /app

COPY ./entrypoints/entrypoint-api-backend.sh /usr/bin
RUN chmod +x /usr/bin/entrypoint-api-backend.sh
ENTRYPOINT ["entrypoint-api-backend.sh"]
EXPOSE 4001

CMD ["rails", "s", "-b", "0.0.0.0"]